on: [push]



jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: zsh version
        run: echo $ZSH_NAME $ZSH_VERSION
        shell: zsh {0}


